spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:app}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:app}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:app}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate      # O schema vem do Flyway

  flyway:
    enabled: true
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration,classpath:db/migration-dev}
    baseline-on-migrate: false
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:app}}
    user: ${SPRING_DATASOURCE_USERNAME:${DB_USER:app}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:app}}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# Dev: CORS amplo (ajuste o origin conforme o front)
app:
  cors:
    allowed-origins: "http://localhost:3000"

springdoc:
  swagger-ui:
    enabled: true

# Actuator => Expondo endpoints internos para monitorar a aplicação (health, info, metrics, env, beans, mappings etc)
management:
  endpoints:
    web:
      exposure:
        include: "*"

api:
  security:
    token:
      secret: PG/7ONpNJspUZUm315FvrtOmn9ZFWAVJJcNaoqDMRiA+n3J3HKL51ZlKYCpvnzWs0Ji5/HiFAzwAxyD/M+UADA==
      expiration: 3600